name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Configurações Gerais
          user: martimgil
          template: classic
          filename: github-metrics.svg
          config_timezone: Europe/Lisbon
          
          # --- ESTATÍSTICAS BÁSICAS (Topo) ---
          # Mostra: Stars, Seguidores, Forks e Repositórios
          base: header, community, repositories
          
          # --- LINGUAGENS (O Mais Usado) ---
          plugin_languages: yes
          plugin_languages_limit: 8           # Apenas as 8 principais
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_ignored: html, css # Ignora linguagens de marcação se preferires
          
          # --- TOTAL DE LINHAS DE CÓDIGO ---
          plugin_lines: yes
          
          # --- CONQUISTAS (Opcional, mas ocupa pouco espaço) ---
          plugin_achievements: yes
          plugin_achievements_display: compact
          
          # Prevenção de timeouts
          retries: 3
          retries_delay: 300
