steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          user: martimgil
          template: classic
          config_timezone: Europe/Lisbon
          
   
          commits_authoring: martimgil@ua.pt, a.martimgil@gmail.com
          
          base: ""
          
          plugin_languages: yes
          
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          # --- GR√ÅFICO 3D ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
