name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: martimgil
          template: classic
          config_timezone: Europe/Lisbon
          commits_authoring: martimgil@ua.pt, a.martimgil@gmail.com
          
          # Removemos 'metadata' para tirar a foto e simplificamos para esconder zeros
          base: header, activity, community, repositories
          
          # --- LINGUAGENS  ---
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_ignored: html, css, tex, shader
          
          # --- GRÁFICO 3D ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # --- PREVENÇÃO DE ERROS E TIMEOUTS ---
          retries: 3
          retries_delay: 300

          # --- HÁBITOS ---
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no 
          plugin_habits_days: 14
          plugin_habits_from: 200
          
          # --- LINHAS DE CÓDIGO ---
          plugin_lines: yes

          # --- CONQUISTAS ---
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_ignored: manager
