name: Metrics
on:
  # Roda todos os dias à meia-noite (Horário de Lisboa)
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Lembre-se de criar este Secret nas settings!

          # Seus dados
          user: martimgil
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Lisbon
          
          # --- O SEGREDO PARA LER ORGS/PRIVADOS ---
          # Coloque o seu email pessoal aqui (o mesmo do git config)
          commits_authoring: a.martimgil@gmail.com
          
          # Configuração de Linguagens (incluindo privados)
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          
          # Mostra linhas de código adicionadas/removidas
          plugin_lines: yes
          
          # Mostra o seu "Streak" (dias seguidos a programar)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
