name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Configurações de Autenticação
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }} # Usa o token padrão para o commit

          # Configurações Gerais
          user: martimgil
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Lisbon
          filename: github-metrics.svg # Define o nome do ficheiro explicitamente

          # Commits
          commits_authoring: martimgil@ua.pt, a.martimgil@gmail.com
          
          # --- LINGUAGENS ---
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          # --- GRÁFICO 3D ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # --- PREVENÇÃO DE ERROS ---
          retries: 3
          retries_delay: 300

          # --- HÁBITOS ---
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no 
          plugin_habits_days: 14
          plugin_habits_from: 200
          
          # --- LINHAS DE CÓDIGO ---
          plugin_lines: yes

          # --- CONQUISTAS ---
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_ignored: manager
